const photographs = [
  {
    id: 25,
    src: "/photos/sunset-of-shichahai.jpg",
    alt: "ShiChaHai sunset",
    title: "ShiChaHai Sunset",
    description: "Beautiful sunset over Beijing's ShiChaHai.",
    span: "normal" as const,
    aspectRatio: "1978/1280",
  },
  {
    id: 31,
    src: "/photos/yellow-taxi.jpg",
    alt: "Yellow taxi",
    title: "Yellow Taxi",
    description: 'The famous "Yellow Ferrari" taxis at Chongqing\'s airports.',
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 32,
    src: "/photos/yulan-flower.jpg",
    alt: "Yulan magnolia flower",
    title: "Yulan Flower",
    description:
      "The red walls and blooming flowers complement each other beautifully.",
    span: "normal" as const,
    aspectRatio: "1996/1280",
  },
  {
    id: 5,
    src: "/photos/classic-jurassic-car.jpg",
    alt: "Vintage car photography",
    title: "Classic Jurassic Car",
    description: "A super cool Jeep with the classic Jurassic Park print.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 6,
    src: "/photos/cyber-chongqing.jpg",
    alt: "Cyberpunk Chongqing",
    title: "Cyber Chongqing",
    description: "The cyberpunk aesthetic of Chongqing's night skyline.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 19,
    src: "/photos/qingdao-sea.jpg",
    alt: "Qingdao seascape",
    title: "Qingdao Blue",
    description: "The lush green trees, vast sea and soft beaches in Qingdao.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 11,
    src: "/photos/green-orange.jpg",
    alt: "Green Orange",
    title: "Green Orange",
    description: "Juicy green oranges glistening with freshness.",
    span: "normal" as const,
    aspectRatio: "1709/1280",
  },
  {
    id: 9,
    src: "/photos/fisherman.jpg",
    alt: "Fishing by the water",
    title: "The Fisherman",
    description:
      "In black and white, a solitary yet courageous fisherman casting his line alone.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 7,
    src: "/photos/dajie-spring-festival.jpg",
    alt: "Spring Festival celebration",
    title: "Spring Festival",
    description:
      "The vibrant atmosphere of Spring Festival celebration in my hometown.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 27,
    src: "/photos/temple-of-heaven.jpg",
    alt: "Temple of Heaven",
    title: "Beijing's Temple of Heaven",
    description: "The grand Temple of Heaven in Beijing.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 2,
    src: "/photos/boy-in-autumn.jpg",
    alt: "Boy enjoying autumn",
    title: "Autumn Boy",
    description:
      "A boy wanders in a late autumn park, covered with fallen leaves.",
    span: "tall" as const,
    aspectRatio: "1330/2364",
  },
  {
    id: 1,
    src: "/photos/beijing-street.jpg",
    alt: "Beijing street",
    title: "Beijing Street",
    description:
      "Beijing, after the rain, autumn street snap, deep green tones.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 3,
    src: "/photos/cat.jpg",
    alt: "Cat photography",
    title: "A Dominant Cat",
    description: "A dominant cat stares forward into the wind.",
    span: "normal" as const,
    aspectRatio: "1480/962",
  },
  {
    id: 4,
    src: "/photos/yangtze-river-bridge.jpg",
    alt: "Yangtze River bridge",
    title: "Yangtze River Bridge",
    description: "Wuhan Yangtze River Bridge at dusk.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 8,
    src: "/photos/doge.jpg",
    alt: "Doge portrait",
    title: "Such Wow",
    description: "A Doge getting petted into airplane ears mode.",
    span: "tall" as const,
    aspectRatio: "1280/1782",
  },
  {
    id: 10,
    src: "/photos/sea-parasailing.jpg",
    alt: "Sea Parasailing",
    title: "Sea Parasailing",
    description: "Feel the wind of freedom over the sea.",
    span: "tall" as const,
    aspectRatio: "960/1440",
  },
  {
    id: 12,
    src: "/photos/withered-wood.jpg",
    alt: "Withered Wood",
    title: "Withered Wood",
    description: "Surrounded by lush greenery, it lies withered.",
    span: "tall" as const,
    aspectRatio: "1279/2214",
  },
  {
    id: 13,
    src: "/photos/hongyadong.jpg",
    alt: "Hongya Cave Chongqing",
    title: "Hongya Cave",
    description: "The iconic Hongya Cave in Chongqing, lit up at night.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 14,
    src: "/photos/labubu.jpg",
    alt: "Labubu toy art",
    title: "Labubu",
    description: "A cute and artistic Labubu collectible.",
    span: "tall" as const,
    aspectRatio: "1280/1396",
  },
  {
    id: 15,
    src: "/photos/laifushi.jpg",
    alt: "Laifushi",
    title: "Laifushi",
    description: "Busy crowds in front of Chongqing Laifushi.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 16,
    src: "/photos/long-expose-sea.jpg",
    alt: "Long exposure seascape",
    title: "The tranquil sea",
    description: "The sea is smoothed into stillness by a long exposure.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 17,
    src: "/photos/modern-tall-buildings.jpg",
    alt: "Modern city skyline",
    title: "Shanghai Skyline",
    description: "A vibrant city skyline in Shanghai.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 18,
    src: "/photos/qingdao-bus.jpg",
    alt: "Qingdao street",
    title: "Qingdao Street",
    description: "Qingdao, a city full of exotic charm.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 20,
    src: "/photos/sea-and-boat.jpg",
    alt: "Cargo ships at sea",
    title: "Cargo ships at sea",
    description: "Cargo ships sail and work on the sea day in and day out.",
    span: "normal" as const,
    aspectRatio: "2033/1279",
  },
  {
    id: 21,
    src: "/photos/sea-and-sunset.jpg",
    alt: "Sunset over the sea",
    title: "Golden Sunset",
    description: "The golden hour casting its magic over the sea.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 22,
    src: "/photos/shanghai-teal-orange.jpg",
    alt: "Shanghai teal orange",
    title: "Shanghai Hues",
    description: "Shanghai in teal and orange tones.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 23,
    src: "/photos/shanghai-long-expose.jpg",
    alt: "Shanghai long exposure",
    title: "Shanghai Flow",
    description: "Long exposure of Shanghai's traditional flow.",
    span: "tall" as const,
    aspectRatio: "1280/1770",
  },
  {
    id: 24,
    src: "/photos/shanghai-night.jpg",
    alt: "Shanghai night view",
    title: "Shanghai Nights",
    description: "Shot of the Huangpu River and Pudong skyline at night.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 26,
    src: "/photos/temple.jpg",
    alt: "Temple architecture",
    title: "Temple and Flowers",
    description: "Temples in Beijing's Beihai Park in spring.",
    span: "normal" as const,
    aspectRatio: "1935/1280",
  },
  {
    id: 28,
    src: "/photos/train-through-the-building.jpg",
    alt: "Train through building",
    title: "Train through Building",
    description:
      "The light rail passing through buildings can only be seen in Chongqing.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 29,
    src: "/photos/tree-of-xiaomaidao.jpg",
    alt: "A tree",
    title: "A Tree",
    description: "A lonely tree standing tall at Xiaomai Island.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 30,
    src: "/photos/xian-buddha.jpg",
    alt: "Xian Buddha",
    title: "Xian Buddha",
    description: "Pillars with numerous Buddha statues in Xi'an.",
    span: "tall" as const,
    aspectRatio: "1280/2020",
  },
  {
    id: 33,
    src: "/photos/yunmeng-mountain.jpg",
    alt: "Yunmeng Mountain",
    title: "Yunmeng Mountain",
    description: "The magnificent scenery of Yunmeng Mountain.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
];

export { photographs };
export type Photograph = (typeof photographs)[number];
