const photographs = [
  {
    id: 25,
    src: "/photos/sunset-of-shichahai.jpg",
    alt: "ShiChaHai sunset",
    title: "ShiChaHai Sunset",
    description: "Beautiful sunset over Beijing's ShiChaHai.",
    span: "normal" as const,
    aspectRatio: "1978/1280",
  },
  {
    id: 31,
    src: "/photos/yellow-taxi.jpg",
    alt: "Yellow taxi",
    title: "Yellow Taxi",
    description: 'The famous "Yellow Ferrari" taxis at Chongqing\'s airports.',
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 32,
    src: "/photos/yulan-flower.jpg",
    alt: "Yulan magnolia flower",
    title: "Yulan Flower",
    description:
      "The red walls and blooming flowers complement each other beautifully.",
    span: "normal" as const,
    aspectRatio: "1996/1280",
  },
  {
    id: 5,
    src: "/photos/classic-jurassic-car.jpg",
    alt: "Vintage car photography",
    title: "Classic Jurassic Car",
    description: "A super cool Jeep with the classic Jurassic Park print.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 6,
    src: "/photos/cyber-chongqing.jpg",
    alt: "Cyberpunk Chongqing",
    title: "Cyber Chongqing",
    description: "The cyberpunk aesthetic of Chongqing's night skyline.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 19,
    src: "/photos/qingdao-sea.jpg",
    alt: "Qingdao seascape",
    title: "Qingdao Blue",
    description: "The lush green trees, vast sea and soft beaches in Qingdao.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 11,
    src: "/photos/green-orange.jpg",
    alt: "Green Orange",
    title: "Green Orange",
    description: "Juicy green oranges glistening with freshness.",
    span: "normal" as const,
    aspectRatio: "1709/1280",
  },
  {
    id: 9,
    src: "/photos/fisherman.jpg",
    alt: "Fishing by the water",
    title: "The Fisherman",
    description:
      "In black and white, a solitary yet courageous fisherman casting his line alone.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 7,
    src: "/photos/dajie-spring-festival.jpg",
    alt: "Spring Festival celebration",
    title: "Spring Festival",
    description:
      "The vibrant atmosphere of Spring Festival celebration in my hometown.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 27,
    src: "/photos/temple-of-heaven.jpg",
    alt: "Temple of Heaven",
    title: "Beijing's Temple of Heaven",
    description: "The grand Temple of Heaven in Beijing.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 2,
    src: "/photos/boy-in-autumn.jpg",
    alt: "Boy enjoying autumn",
    title: "Autumn Boy",
    description:
      "A boy wanders in a late autumn park, covered with fallen leaves.",
    span: "tall" as const,
    aspectRatio: "1330/2364",
  },
  {
    id: 1,
    src: "/photos/beijing-street.jpg",
    alt: "Beijing street",
    title: "Beijing Street",
    description:
      "Beijing, after the rain, autumn street snap, deep green tones.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 3,
    src: "/photos/cat.jpg",
    alt: "Cat photography",
    title: "A Dominant Cat",
    description: "A dominant cat stares forward into the wind.",
    span: "normal" as const,
    aspectRatio: "1480/962",
  },
  {
    id: 4,
    src: "/photos/yangtze-river-bridge.jpg",
    alt: "Yangtze River bridge",
    title: "Yangtze River Bridge",
    description: "Wuhan Yangtze River Bridge at dusk.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 8,
    src: "/photos/doge.jpg",
    alt: "Doge portrait",
    title: "Such Wow",
    description: "A Doge getting petted into airplane ears mode.",
    span: "tall" as const,
    aspectRatio: "1280/1782",
  },
  {
    id: 10,
    src: "/photos/sea-parasailing.jpg",
    alt: "Sea Parasailing",
    title: "Sea Parasailing",
    description: "Feel the wind of freedom over the sea.",
    span: "tall" as const,
    aspectRatio: "960/1440",
  },
  {
    id: 12,
    src: "/photos/withered-wood.jpg",
    alt: "Withered Wood",
    title: "Withered Wood",
    description: "Surrounded by lush greenery, it lies withered.",
    span: "tall" as const,
    aspectRatio: "1279/2214",
  },
  {
    id: 13,
    src: "/photos/hongyadong.jpg",
    alt: "Hongya Cave Chongqing",
    title: "Hongya Cave",
    description: "The iconic Hongya Cave in Chongqing, lit up at night.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 14,
    src: "/photos/labubu.jpg",
    alt: "Labubu toy art",
    title: "Labubu",
    description: "A cute and artistic Labubu collectible.",
    span: "tall" as const,
    aspectRatio: "1280/1396",
  },
  {
    id: 15,
    src: "/photos/laifushi.jpg",
    alt: "Laifushi",
    title: "Laifushi",
    description: "Busy crowds in front of Chongqing Laifushi.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 16,
    src: "/photos/long-expose-sea.jpg",
    alt: "Long exposure seascape",
    title: "The tranquil sea",
    description: "The sea is smoothed into stillness by a long exposure.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 17,
    src: "/photos/modern-tall-buildings.jpg",
    alt: "Modern city skyline",
    title: "Shanghai Skyline",
    description: "A vibrant city skyline in Shanghai.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 18,
    src: "/photos/qingdao-bus.jpg",
    alt: "Qingdao street",
    title: "Qingdao Street",
    description: "Qingdao, a city full of exotic charm.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 20,
    src: "/photos/sea-and-boat.jpg",
    alt: "Cargo ships at sea",
    title: "Cargo ships at sea",
    description: "Cargo ships sail and work on the sea day in and day out.",
    span: "normal" as const,
    aspectRatio: "2033/1279",
  },
  {
    id: 21,
    src: "/photos/sea-and-sunset.jpg",
    alt: "Sunset over the sea",
    title: "Golden Sunset",
    description: "The golden hour casting its magic over the sea.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 22,
    src: "/photos/shanghai-teal-orange.jpg",
    alt: "Shanghai teal orange",
    title: "Shanghai Hues",
    description: "Shanghai in teal and orange tones.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 23,
    src: "/photos/shanghai-long-expose.jpg",
    alt: "Shanghai long exposure",
    title: "Shanghai Flow",
    description: "Long exposure of Shanghai's traditional flow.",
    span: "tall" as const,
    aspectRatio: "1280/1770",
  },
  {
    id: 24,
    src: "/photos/shanghai-night.jpg",
    alt: "Shanghai night view",
    title: "Shanghai Nights",
    description: "Shot of the Huangpu River and Pudong skyline at night.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 26,
    src: "/photos/temple.jpg",
    alt: "Temple architecture",
    title: "Temple and Flowers",
    description: "Temples in Beijing's Beihai Park in spring.",
    span: "normal" as const,
    aspectRatio: "1935/1280",
  },
  {
    id: 28,
    src: "/photos/train-through-the-building.jpg",
    alt: "Train through building",
    title: "Train through Building",
    description:
      "The light rail passing through buildings can only be seen in Chongqing.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 29,
    src: "/photos/tree-of-xiaomaidao.jpg",
    alt: "A tree",
    title: "A Tree",
    description: "A lonely tree standing tall at Xiaomai Island.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 30,
    src: "/photos/xian-buddha.jpg",
    alt: "Xian Buddha",
    title: "Xian Buddha",
    description: "Pillars with numerous Buddha statues in Xi'an.",
    span: "tall" as const,
    aspectRatio: "1280/2020",
  },
  {
    id: 33,
    src: "/photos/yunmeng-mountain.jpg",
    alt: "Yunmeng Mountain",
    title: "Yunmeng Mountain",
    description: "The magnificent scenery of Yunmeng Mountain.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 34,
    src: "/photos/abiao.jpg",
    alt: "Abiao",
    title: "Abiao",
    description: "A moment captured with Abiao.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 35,
    src: "/photos/afternoon-tree.jpg",
    alt: "Afternoon tree",
    title: "Afternoon Tree",
    description: "A tree bathed in warm afternoon light.",
    span: "tall" as const,
    aspectRatio: "1280/1875",
  },
  {
    id: 37,
    src: "/photos/beijing-hutong-2.jpg",
    alt: "Beijing hutong",
    title: "Beijing Hutong II",
    description: "Another glimpse of Beijing's historic hutongs.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 38,
    src: "/photos/black-and-white-fisher.jpg",
    alt: "Black and white fisherman",
    title: "The Fisherman",
    description: "A timeless black and white portrait of a fisherman.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 39,
    src: "/photos/dog-and-cat.jpg",
    alt: "Dog and cat",
    title: "Dog and Cat",
    description: "Unlikely friends sharing a peaceful moment.",
    span: "normal" as const,
    aspectRatio: "1575/1280",
  },
  {
    id: 40,
    src: "/photos/flowers-and-bikes.jpg",
    alt: "Flowers and bikes",
    title: "Flowers and Bikes",
    description: "Blooming flowers alongside parked bicycles.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 41,
    src: "/photos/flowers-in-mirror.jpg",
    alt: "Flowers in mirror",
    title: "Flowers in Mirror",
    description: "A reflection of beautiful flowers in a mirror.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 42,
    src: "/photos/happy-child.jpg",
    alt: "Happy child",
    title: "Happy Child",
    description: "A child's joyful expression captured in time.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 43,
    src: "/photos/leaf-and-grass.jpg",
    alt: "Leaf and grass",
    title: "Leaf and Grass",
    description: "Nature's delicate details in close-up.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 36,
    src: "/photos/beijing-hutong-1.jpg",
    alt: "Beijing hutong",
    title: "Beijing Hutong",
    description: "The traditional alleyways of Beijing.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 44,
    src: "/photos/long-exp-car.jpg",
    alt: "Long exposure car",
    title: "Night Traffic",
    description: "Light trails from cars in a long exposure shot.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 51,
    src: "/photos/white-cat.jpg",
    alt: "White cat",
    title: "White Cat",
    description: "A serene white cat resting peacefully.",
    span: "normal" as const,
    aspectRatio: "1344/960",
  },
  {
    id: 45,
    src: "/photos/love-night.jpg",
    alt: "Love night",
    title: "Love Night",
    description: "Aiwan, which means love night",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 46,
    src: "/photos/paint-for-family.jpg",
    alt: "Paint for family",
    title: "Family Portrait",
    description: "A painted portrait dedicated to family.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 47,
    src: "/photos/photographer.jpg",
    alt: "Photographer",
    title: "The Photographer",
    description: "A photographer at work capturing moments.",
    span: "tall" as const,
    aspectRatio: "960/1440",
  },
  {
    id: 48,
    src: "/photos/qingdao-wall.jpg",
    alt: "Qingdao wall",
    title: "Qingdao Wall",
    description: "A textured wall in the coastal city of Qingdao.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 49,
    src: "/photos/sunset-duck.jpg",
    alt: "Sunset duck",
    title: "Sunset Duck",
    description: "A duck swimming in the golden sunset light.",
    span: "normal" as const,
    aspectRatio: "1919/1281",
  },
  {
    id: 50,
    src: "/photos/twins.jpg",
    alt: "Twins",
    title: "Twins",
    description: "Two of a kind, captured together.",
    span: "tall" as const,
    aspectRatio: "1285/2448",
  },
];

export { photographs };
export type Photograph = (typeof photographs)[number];
