import { SiShopee, SiTencentqq, SiTiktok } from "react-icons/si";

const tags = [
  { name: "TypeScript", category: "Technology" },
  { name: "React", category: "Technology" },
  { name: "Node.js", category: "Technology" },
  { name: "⚽️ Man City", category: "Hobby" },
  { name: "🎮 LOL", category: "Hobby" },
  { name: "🎤 Singing", category: "Hobby" },
  { name: "🚴 Bicycling", category: "Hobby" },
];

const experiences = [
  {
    company: "Tencent",
    icon: <SiTencentqq />,
    position: "Frontend Engineer",
    department: "CDG-AMS",
    period: "2024.06 - Present",
    description:
      "In charge of the low-code platform, PC Advertising SDK, and other related business.",
  },
  {
    company: "ByteDance",
    icon: <SiTiktok />,
    position: "Frontend Engineer",
    department: "Customer Service Platform",
    period: "2022.10 - 2024.06",
    description:
      "Support Douyin's customer service. As a member of the FE arch team, responsible for Hi CLI.",
  },
  {
    company: "Shopee",
    icon: <SiShopee />,
    position: "Frontend Engineer",
    department: "APP Performance",
    period: "2022.07 - 2022.09",
    description: "Laid off as a fresh graduate.",
  },
];

const projects = [
  {
    name: "Chat Desktop App Boilerplate",
    description: "A full-stack AI chatbot desktop app boilerplate",
    tech: ["React", "Bun", "Hono", "PostgreSQL"],
    link: "https://github.com/miownag/chat-desktop-app-boilerplate",
    image: undefined, // Optional: Add image URL here
  },
  {
    name: "Ink Markdown ES",
    description: "A lib for ink to render markdown in TUI",
    tech: ["Ink", "Marked", "highlight.js"],
    link: "https://github.com/miownag/ink-markdown-es",
    image: undefined, // Optional: Add image URL here
  },
  {
    name: "Code Agent Lite",
    description: "Just like Claude Code, but lite",
    tech: ["Ink", "Bun", "LangChain", "deepagents"],
    link: "https://github.com/miownag/code-agent-lite",
    image: undefined, // Optional: Add image URL here
  },
  {
    name: "Billionaire CLI Framework",
    description:
      "A File-based Conventional CLI Framework built on commander.js",
    tech: ["Node.js", "TypeScript", "commander.js"],
    link: "https://github.com/miownag/bn-cli-framework",
    image: undefined, // Optional: Add image URL here
  },
  {
    name: "3Domension",
    description: "3Domension is a lib that can trans DOM into 3 dimension",
    tech: ["CSS3"],
    link: "https://github.com/miownag/three-domension",
    image: undefined, // Optional: Add image URL here
  },
  {
    name: "Open Source Projects",
    description: "Contribute to open source projects and learn from others 😊",
    tech: ["Ant Design", "TDesign", "..."],
    link: "https://github.com/miownag?tab=repositories",
    image: undefined, // Optional: Add image URL here
  },
];

const photographs = [
  {
    id: 1,
    src: "/photos/beijing-street.jpg",
    alt: "Beijing street photography",
    title: "Beijing Street",
    description: "The bustling streets of Beijing capturing daily city life.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 2,
    src: "/photos/boy-in-spring.jpg",
    alt: "Boy enjoying spring",
    title: "Spring Boy",
    description: "A joyful moment of youth in the spring breeze.",
    span: "tall" as const,
    aspectRatio: "1330/2364",
  },
  {
    id: 3,
    src: "/photos/cat.jpg",
    alt: "Cat photography",
    title: "Curious Cat",
    description: "A curious cat exploring quietly.",
    span: "normal" as const,
    aspectRatio: "1480/962",
  },
  {
    id: 4,
    src: "/photos/changjiang-river.jpg",
    alt: "Yangtze River landscape",
    title: "Changjiang River",
    description: "The mighty Yangtze River flowing through the land.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 5,
    src: "/photos/classic-jurassic-car.jpg",
    alt: "Vintage car photography",
    title: "Classic Jurassic Car",
    description: "A timeless beauty of vintage automotive design.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 6,
    src: "/photos/cyber-chongqing.jpg",
    alt: "Cyberpunk Chongqing",
    title: "Cyber Chongqing",
    description: "The cyberpunk aesthetic of Chongqing's night skyline.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 7,
    src: "/photos/dajie-spring-festival.jpg",
    alt: "Spring Festival celebration",
    title: "Spring Festival",
    description: "The vibrant atmosphere of Spring Festival celebration.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 8,
    src: "/photos/doge.jpg",
    alt: "Doge portrait",
    title: "Such Wow",
    description: "The legendary Shiba Inu in all its glory.",
    span: "tall" as const,
    aspectRatio: "1280/1782",
  },
  {
    id: 9,
    src: "/photos/fisherman.jpg",
    alt: "Fishing by the water",
    title: "The Fisherman",
    description: "A peaceful moment by the water's edge.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 10,
    src: "/photos/fly-umbrella.jpg",
    alt: "Umbrella with fly",
    title: "Umbrella Fly",
    description: "An artistic play of light and shadow with an umbrella.",
    span: "tall" as const,
    aspectRatio: "960/1440",
  },
  {
    id: 11,
    src: "/photos/green-orange.jpg",
    alt: "Green and orange colors",
    title: "Green Orange",
    description: "A striking color composition of green and orange.",
    span: "normal" as const,
    aspectRatio: "1709/1280",
  },
  {
    id: 12,
    src: "/photos/green-tree.jpg",
    alt: "Green tree photography",
    title: "Green Tree",
    description: "The vitality of nature captured in a single tree.",
    span: "tall" as const,
    aspectRatio: "1279/2214",
  },
  {
    id: 13,
    src: "/photos/hongyadong.jpg",
    alt: "Hongya Cave Chongqing",
    title: "Hongya Cave",
    description: "The iconic Hongya Cave in Chongqing, lit up at night.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 14,
    src: "/photos/labubu.jpg",
    alt: "Labubu toy art",
    title: "Labubu",
    description: "A cute and artistic Labubu collectible.",
    span: "tall" as const,
    aspectRatio: "1280/1396",
  },
  {
    id: 15,
    src: "/photos/laifushi.jpg",
    alt: "Laifushi scenery",
    title: "Laifushi",
    description: "Scenic views from Laifushi.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 16,
    src: "/photos/long-expose-sea.jpg",
    alt: "Long exposure seascape",
    title: "Flowing Sea",
    description: "The ethereal beauty of long exposure seascape.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 17,
    src: "/photos/modern-tall-buildings.jpg",
    alt: "Modern city skyline",
    title: "Tall Towers",
    description: "Rising skyscrapers defining the modern city skyline.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 18,
    src: "/photos/qingdao-bus.jpg",
    alt: "Qingdao street",
    title: "Qingdao Street",
    description: "A quiet street scene in Qingdao.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 19,
    src: "/photos/qingdao-sea.jpg",
    alt: "Qingdao seascape",
    title: "Qingdao Blue",
    description: "The calming blue of Qingdao's coastal waters.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 20,
    src: "/photos/sea-and-boat.jpg",
    alt: "Boat at sea",
    title: "Sea & Boat",
    description: "A solitary boat navigating the open sea.",
    span: "normal" as const,
    aspectRatio: "2033/1279",
  },
  {
    id: 21,
    src: "/photos/sea-and-sunset.jpg",
    alt: "Sunset over the sea",
    title: "Golden Sunset",
    description: "The golden hour casting its magic over the sea.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 22,
    src: "/photos/shanghai-cyan-orange.jpg",
    alt: "Shanghai cyan orange",
    title: "Shanghai Hues",
    description: "A striking color study of Shanghai at dusk.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 23,
    src: "/photos/shanghai-long-expose.jpg",
    alt: "Shanghai long exposure",
    title: "Shanghai Flow",
    description: "Long exposure revealing the rhythm of Shanghai night life.",
    span: "tall" as const,
    aspectRatio: "1280/1770",
  },
  {
    id: 24,
    src: "/photos/shanghai-night.jpg",
    alt: "Shanghai night view",
    title: "Shanghai Nights",
    description: "The dazzling lights of Shanghai after dark.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 25,
    src: "/photos/sunset-of-shichahai.jpg",
    alt: "Shichahai sunset",
    title: "Shichahai Sunset",
    description: "Sunset reflections in Shichahai, Beijing.",
    span: "normal" as const,
    aspectRatio: "1978/1280",
  },
  {
    id: 26,
    src: "/photos/temple.jpg",
    alt: "Temple architecture",
    title: "Ancient Temple",
    description: "Traditional architecture capturing timeless wisdom.",
    span: "normal" as const,
    aspectRatio: "1935/1280",
  },
  {
    id: 27,
    src: "/photos/tiantan.jpg",
    alt: "Temple of Heaven",
    title: "Tian Tan",
    description: "The majestic Temple of Heaven in Beijing.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 28,
    src: "/photos/train-throught-the-building.jpg",
    alt: "Train through building",
    title: "Liuzhou Train",
    description: "The unique train passing through a building in Liuzhou.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
  {
    id: 29,
    src: "/photos/tree-of-xiaomaidao.jpg",
    alt: "Xiaomaidao tree",
    title: "Xiaomaidao Tree",
    description: "A lonely tree standing tall at Xiaomaidao.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 30,
    src: "/photos/xian-fo.jpg",
    alt: "Giant Wild Goose Pagoda",
    title: "Xian Buddha",
    description: "The sacred Giant Wild Goose Pagoda in Xi'an.",
    span: "tall" as const,
    aspectRatio: "1280/2020",
  },
  {
    id: 31,
    src: "/photos/yellow-taxi.jpg",
    alt: "Yellow taxi",
    title: "Yellow Taxi",
    description: "A splash of yellow in the urban landscape.",
    span: "tall" as const,
    aspectRatio: "1280/1920",
  },
  {
    id: 32,
    src: "/photos/yulan-flower.jpg",
    alt: "Yulan magnolia flower",
    title: "Yulan Flower",
    description: "The elegant beauty of magnolia in full bloom.",
    span: "normal" as const,
    aspectRatio: "1996/1280",
  },
  {
    id: 33,
    src: "/photos/yunmeng-moutain.jpg",
    alt: "Yunmeng Mountain",
    title: "Yunmeng Mountain",
    description: "Mist-covered peaks of Yunmeng Mountain.",
    span: "normal" as const,
    aspectRatio: "1920/1280",
  },
];

const recentLearning = [
  {
    title: "Signs of introspection in large language models",
    source: "Anthropic",
    date: "2025-12",
    tags: ["AI", "LLM", "Introspection"],
    link: "https://www.anthropic.com/research/introspection",
  },
  {
    title: "Context Engineering for AI Agents: Lessons from Building Manus",
    source: "Manus",
    date: "2025-07",
    tags: ["Context Engineering", "Agent", "LLM"],
    link: "https://manus.im/blog/Context-Engineering-for-AI-Agents-Lessons-from-Building-Manus",
  },
  {
    title: "DeepWiki",
    source: "Devin",
    tags: ["Learning"],
    link: "https://deepwiki.com",
  },
];

export { tags, experiences, projects, photographs, recentLearning };
export type Photograph = (typeof photographs)[number];
